### PR TITLE
Fixes #16402 - print valid message  incase wrong policy

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by shlomizadok** [comment]
@ranjan - Thank you so much for this addition. It works perfectly.
However, I wonder if we should somehow notify elsewhere (foreman? proxy?) about the failure. The ratio behind this is that `foreman_scap_client ID` usually runs in a cron jon, so we may not see this notification (unless running it manually).
This may be sufficient to begin with - but we should bare in mind to maybe extract it.
@xprazak2, @ares - what do you think?

**Comment by xprazak2** [comment]
I have no objections here, this is great when running `foreman_scap_client` manually. If running from cron fails for whatever reason, we will not see anything anyway, because all our logging is just text printed to console with `puts`.

I think the next step would be to add a log file for client - I personally like this. I am not sure about the benefit of sending client errors through proxy. config.yml and crons are managed by Puppet, so if puppet-foreman_scap_client is broken, we will find out pretty soon since all clients will have failures. I think there is bigger chance of proxy being down/unreachable then failure of running cron.

**Comment by shlomizadok** [comment]
@xprazak2 - thanks for you input.
@ranjan - Merging. Thanks a lot!
Will you please add an issue (feature) to add some sort of logging?

**Comment by ares** [comment]
maybe just exposing MAILTO of cron.d file could be an alternative but we already print some messages which is why we redirect stdout to /dev/null IIRC, anyway let's discuss it on that new ticket

**Pull request merged**
