### PR TITLE
Send bzip2ed ARF reports.

### LINKED ISSUE #4: bzip2ed xml should be sent
Currently we send XML without compression over the network. Foreman assumes bzip2ed xml and fails with

```
Could not read from bz_stream: BZ2_bzDecompress returns -5 [bz2.c:157]
Could not create Result DataStream session: File is not Result DataStream. [ds_rds_session.c:54]
 (OpenSCAP::OpenSCAPError)
/opt/rh/ruby193/root/usr/share/gems/gems/openscap-0.4.2/lib/openscap/openscap.rb:34:in `raise!'
/opt/rh/ruby193/root/usr/share/gems/gems/openscap-0.4.2/lib/openscap/ds/arf.rb:30:in `initialize'
/opt/rh/ruby193/root/usr/share/gems/gems/scaptimony-0.2.0/app/models/scaptimony/arf_report_raw.rb:48:in `new'
/opt/rh/ruby193/root/usr/share/gems/gems/scaptimony-0.2.0/app/models/scaptimony/arf_report_raw.rb:48:in `build_arf'
/opt/rh/ruby193/root/usr/share/gems/gems/scaptimony-0.2.0/app/models/scaptimony/arf_report_raw.rb:26:in `save_dependent_entities'
```

### PR DESCRIPTION
**Pull request by isimluk**
Foreman_openscap receives only bzip2ed arfs.

Fixes #4.

### CODE REVIEW

**Comment by shlomizadok** [comment]
Is there a way for us to ensure `/usr/bin/bzip2` actually exists?

**Comment by isimluk** [comment]
Good point. Added as rpm dependency. Does gem spec allow for external dependencies?

**Comment by shlomizadok** [comment]
http://guides.rubygems.org/specification-reference/#requirements

**Comment by shlomizadok** [comment]
lgtm, work great. ready to merge

**Pull request merged**
