### PR TITLE
Fixes #25959 - Show warnings for remote resources

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
@san7ket could you verify this? should be easy

**Comment by san7ket** [comment]
@ares on it

**Comment by san7ket** [comment]
ACK, works as expected 
Without the fix: 
```
foreman_scap_client 1
DEBUG: running: oscap xccdf eval  --profile xccdf_org.ssgproject.content_profile_rht-ccp  --results-arf /tmp/d20190212-2450-40cdr3/results.xml /var/lib/openscap/content/96c2a9d5278d5da905221bbb2dc61d0ace7ee3d97f021fccac994d26296d986d.xml
DEBUG: running: /usr/bin/env bzip2 /tmp/d20190212-2450-40cdr3/results.xml
Uploading results to https://sat:9090/compliance/arf/1
Report uploaded, report id: 594
```
After the fix:
```
foreman_scap_client 1
DEBUG: running: oscap xccdf eval  --profile xccdf_org.ssgproject.content_profile_rht-ccp  --results-arf /tmp/d20190212-2844-11onupu/results.xml /var/lib/openscap/content/96c2a9d5278d5da905221bbb2dc61d0ace7ee3d97f021fccac994d26296d986d.xml
WARNING: This content points out to the remote resources. Use `--fetch-remote-resources' option to download them.
WARNING: Skipping https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2 file which is referenced from XCCDF content
DEBUG: running: /usr/bin/env bzip2 /tmp/d20190212-2844-11onupu/results.xml
Uploading results to https://sat:9090/compliance/arf/1
Report uploaded, report id: 595
```

**Comment by ares** [comment]
Thanks @xprazak2 and @san7ket, merging!

**Pull request merged**
