### PR TITLE
Fixes #31038 - Add scanning with OVAL files

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Most changes are just moving methods around - most of the logic was moved to a base client class.

**Comment by ares** [comment]
Could a policy have a type, so we don't have to specify it when running foreman_scan_client? That way users don't have to modify cron jobs. If it makes too many changes, we could only add that to oval, if type is not specified for the policy, it would be considered ds.

**Comment by xprazak2** [comment]
Policies could have a type, though I am not sure how that would allow us to omit the type when calling foreman_scap_client. I am thinking about cases when users assign both policy types which could have same ids:

```yaml
1:
  :profile: ''
  :content_path: /var/lib/xml/whatever.xml
  :type: ds

1:
  :content_path: /var/lib/xml/oval/test.xml
  :type: oval
```

Namespacing policy entries in config achieves the same as adding type and righ now, we should be backward compatible - `foreman_scap_client 1` should work for existing policies. We could deprecate and move to `foreman_scap_client ds 1` if we choose to.

**Comment by ares** [comment]
oh I was under the impressions policies use STI so they could never have the same ID. However I now realized they just import the common module. OK, I think you're right, as long as the `foreman_scap_client 1` defaults to ds, that's fine :+1:

**Comment by xprazak2** [comment]
I pushed a change that pluralizes upload path.

**Review by ares — APPROVED** [review]
Thanks, merging! Worth a major bump release :-)

**Pull request merged**
